name: Keep Render Site Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # 每10分钟执行一次
  workflow_dispatch:         # 允许你手动触发

jobs:
  ping-render-site:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to Render site
        run: curl -s https://drivesafenow.onrender.com/
